# Generated by Django 4.2.25 on 2025-11-15 22:17

from django.db import migrations


def populate_user_profiles(apps, schema_editor):
    """
    Create UserProfile for all existing Django User instances and link to Employee records.
    Assign default "Employee" role to all existing users.
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('authentication', 'UserProfile')
    Employee = apps.get_model('employee_management', 'Employee')
    Group = apps.get_model('auth', 'Group')
    RoleAssignment = apps.get_model('authentication', 'RoleAssignment')
    
    # Get or create the default "Employee" role
    employee_role, created = Group.objects.get_or_create(name='Employee')
    
    # Track statistics
    profiles_created = 0
    profiles_linked = 0
    roles_assigned = 0
    
    # Process all existing users
    for user in User.objects.all():
        # Check if UserProfile already exists
        if not hasattr(user, 'profile'):
            # Create UserProfile for this user
            profile = UserProfile.objects.create(user=user)
            profiles_created += 1
            
            # Try to link to Employee record based on email matching
            try:
                # Try to match by username (if it's an email) or by personalEmail
                employee = None
                
                # First try: match username if it looks like an email
                if '@' in user.username:
                    try:
                        employee = Employee.objects.get(personalEmail=user.username)
                    except Employee.DoesNotExist:
                        pass
                
                # Second try: match by user.email field
                if not employee and user.email:
                    try:
                        employee = Employee.objects.get(personalEmail=user.email)
                    except Employee.DoesNotExist:
                        pass
                
                # If we found a matching employee, link it
                if employee:
                    profile.employee = employee
                    profile.department = employee.department
                    profile.save()
                    profiles_linked += 1
                    
            except Exception as e:
                # Continue processing other users if one fails
                print(f"Warning: Could not link user {user.username} to employee: {e}")
        else:
            profile = user.profile
        
        # Assign default "Employee" role if user doesn't have any roles
        if not user.groups.exists():
            user.groups.add(employee_role)
            
            # Create RoleAssignment record for audit trail
            RoleAssignment.objects.create(
                user=user,
                role=employee_role,
                assigned_by=None,  # System assignment
                is_active=True,
                notes="Automatically assigned during data migration"
            )
            roles_assigned += 1
    
    print(f"\nData Migration Summary:")
    print(f"- UserProfiles created: {profiles_created}")
    print(f"- UserProfiles linked to Employee records: {profiles_linked}")
    print(f"- Default 'Employee' roles assigned: {roles_assigned}")


def reverse_populate_user_profiles(apps, schema_editor):
    """
    Reverse migration - remove UserProfiles and role assignments created by this migration.
    """
    UserProfile = apps.get_model('authentication', 'UserProfile')
    RoleAssignment = apps.get_model('authentication', 'RoleAssignment')
    
    # Delete role assignments created by this migration
    RoleAssignment.objects.filter(
        notes="Automatically assigned during data migration"
    ).delete()
    
    # Note: We don't delete UserProfiles as they might have been modified
    # and contain important data. Manual cleanup may be required.
    print("Reverse migration: Removed auto-assigned role assignments")


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auditlog_roleassignment_userprofile_delete_profile"),
        ("employee_management", "0002_alter_employee_options"),  # Ensure Employee model exists
    ]

    operations = [
        migrations.RunPython(populate_user_profiles, reverse_populate_user_profiles),
    ]
