# Generated by Django 4.2.25 on 2025-11-20 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_alter_employee_mobilenumber_and_more'),
        ('authentication', '0005_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Phone Auth Attempt',
                'verbose_name_plural': 'Phone Auth Attempts',
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['email', '-attempt_time'], name='authenticat_email_9328be_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountSetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_tokens', to='employee_management.employee')),
            ],
            options={
                'verbose_name': 'Account Setup Token',
                'verbose_name_plural': 'Account Setup Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
