# Generated by Django 4.2.25 on 2025-11-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_phoneauthattempt_accountsetuptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetuptoken',
            name='current_step',
            field=models.CharField(choices=[('phone_auth', 'Phone Authentication'), ('username_generation', 'Username Generation'), ('password_setup', 'Password Setup'), ('completed', 'Completed')], default='phone_auth', help_text='Current step in the activation flow', max_length=50),
        ),
        migrations.AddField(
            model_name='accountsetuptoken',
            name='generated_username',
            field=models.CharField(blank=True, help_text='Username generated during the flow', max_length=150),
        ),
        migrations.AddField(
            model_name='accountsetuptoken',
            name='password_setup_completed',
            field=models.BooleanField(default=False, help_text='Whether password setup step is completed'),
        ),
        migrations.AddField(
            model_name='accountsetuptoken',
            name='password_setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountsetuptoken',
            name='phone_auth_completed',
            field=models.BooleanField(default=False, help_text='Whether phone authentication step is completed'),
        ),
        migrations.AddField(
            model_name='accountsetuptoken',
            name='phone_auth_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountsetuptoken',
            name='username_generation_completed',
            field=models.BooleanField(default=False, help_text='Whether username generation step is completed'),
        ),
        migrations.AddField(
            model_name='accountsetuptoken',
            name='username_generation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
