# Generated by Django 4.2.25 on 2025-11-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_accountsetuptoken_current_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ROLE_ASSIGNED', 'Role Assigned'), ('ROLE_REVOKED', 'Role Revoked'), ('PERMISSION_CHANGED', 'Permission Changed'), ('ACCESS_DENIED', 'Access Denied'), ('EMPLOYEE_CREATED', 'Employee Created'), ('ACCOUNT_CREATED', 'Account Created'), ('EMAIL_SENT', 'Email Sent'), ('EMAIL_FAILED', 'Email Failed'), ('AUTH_ATTEMPT', 'Authentication Attempt'), ('AUTH_SUCCESS', 'Authentication Success'), ('AUTH_FAILED', 'Authentication Failed'), ('ACCOUNT_ACTIVATED', 'Account Activated')], max_length=50),
        ),
    ]
