# Generated by Django 5.2.6 on 2025-11-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={
                "permissions": [
                    ("view_all_leaves", "Can view all leave requests"),
                    ("view_department_leaves", "Can view department leave requests"),
                    ("approve_leaves", "Can approve leave requests"),
                    ("manage_own_leaves", "Can manage own leave requests"),
                ]
            },
        ),
    ]
