# Generated by Django 5.2.6 on 2025-11-18 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0003_employeedocument"),
        ("leave_management", "0002_alter_leaverequest_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Casual", "Casual Leave"),
                            ("Sick", "Sick Leave"),
                            ("Vacation", "Vacation Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "total",
                    models.IntegerField(
                        default=0, help_text="Total leave days allocated"
                    ),
                ),
                ("used", models.IntegerField(default=0, help_text="Leave days used")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="employee_management.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
                "unique_together": {("employee", "leave_type")},
            },
        ),
    ]
