# Generated by Django 5.2.7 on 2025-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('employeeId', models.CharField(max_length=20, unique=True)),
                ('personalEmail', models.EmailField(max_length=100, unique=True)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('joiningDate', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
