# Generated by Django 5.2.6 on 2025-11-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "permissions": [
                    ("view_all_employees", "Can view all employees"),
                    ("view_department_employees", "Can view department employees"),
                    ("manage_employees", "Can manage employees"),
                ]
            },
        ),
    ]
