# Generated by Django 5.2.6 on 2025-11-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0003_employeedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emergencyContactEmail",
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergencyContactName",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergencyContactPhone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergencyContactRelationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="employmentStatus",
            field=models.CharField(blank=True, default="Active", max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="officeLocation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="preferredName",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="profilePhoto",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_photos/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="reportingManager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="employee_management.employee",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="schoolFaculty",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="workEmail",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="workPhone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
