# Generated by Django 4.2.25 on 2025-11-19 19:57

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_employee_emergencycontactemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobileNumber',
            field=models.CharField(help_text='Phone number with country code (e.g., +919876543210)', max_length=20, validators=[authentication.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personalEmail',
            field=models.EmailField(help_text='Valid email address for account creation', max_length=100, unique=True, validators=[authentication.validators.validate_email_format]),
        ),
    ]
