# Generated by Django 4.2.25 on 2025-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_management",
            "0006_department_designation_employee_department_new_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="designation",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="designation",
            unique_together={("title", "department")},
        ),
    ]
