# Generated by Django 4.2.25 on 2025-11-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0007_alter_designation_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profilePhoto',
        ),
        migrations.AddField(
            model_name='employee',
            name='bankAccountNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(default='Full Time Employees', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='experienceYears',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='highestQualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifscCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='maritalStatus',
            field=models.CharField(default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='panNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanentAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='presentAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='previousInstitution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='probationPeriod',
            field=models.IntegerField(blank=True, default=0, help_text='In months', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/'),
        ),
    ]
