# Generated by Django 4.2.25 on 2025-11-21 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the announcement', max_length=255)),
                ('content', models.TextField(help_text='Full content of the announcement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the announcement is currently active/visible')),
                ('author', models.ForeignKey(help_text='User who created the announcement', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='announcemen_created_da46df_idx'), models.Index(fields=['is_active'], name='announcemen_is_acti_a26055_idx')],
            },
        ),
    ]
