# Generated by Django 5.2.6 on 2025-11-18 11:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee_management", "0003_employeedocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Late", "Late"),
                            ("Half Day", "Half Day"),
                        ],
                        default="Absent",
                        max_length=20,
                    ),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=4
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employee_management.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="attendance__employe_ee9d1b_idx",
                    ),
                    models.Index(fields=["date"], name="attendance__date_02aea3_idx"),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
