# Generated by Django 4.2.25 on 2026-02-06 11:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_leave", "0002_attendancerecord_check_in_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_start", models.TimeField()),
                ("break_end", models.TimeField(blank=True, null=True)),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Duration in hours",
                        max_digits=4,
                    ),
                ),
                (
                    "attendance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="attendance_leave.attendancerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Break",
                "verbose_name_plural": "Attendance Breaks",
                "ordering": ["break_start"],
            },
        ),
    ]
