# Generated by Django 4.2.25 on 2026-02-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_leave", "0003_attendancebreak"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="check_in_address",
            field=models.TextField(
                blank=True, help_text="Human readable address", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="check_out_address",
            field=models.TextField(
                blank=True, help_text="Human readable address", null=True
            ),
        ),
    ]
